print('Hello Python, I am Chizom')
print('')
print('')
print('Chizom, let\'s draw a dog')
print('')
print('o----\\')
print(' /\\ /\\')
print('')
print('')
print('Chizom, here are 7 stars for what you just drew:')
print('* ' * 7)
print('')
print('')
print('Chizom, why don\'t we draw a box?')
print('Chizom: cool')
print('')
print('')
print('. ' * 7)
print('.           .')
print('.           .')
print('.           .')
print('.           .')
print('. ' * 7)
print('We have a box. Yes!')
